.lando.yml, orch/start_storty_book_docker.js
=> fixes #19: Start storybook as node user and set memory on the npm start.

stories/assets/styles/global/index.scss, stories/components/callout/callout.html.twig, stories/components/callout/callout.scss, stories/components/contact-us/contact-us.html.twig, stories/components/contact-us/contact-us.scss, stories/components/section/section.html.twig, stories/components/section/section.scss, stories/components/typography/typography.html.twig
**Visual refinements to Contact Us.** Contact us component looks closer to final version. Closes #17.
**Mobile**
**Desktop**
=> Feature: Refine Contact Us component

.gitignore, .lando.yml, .run/appserver.run.xml, .vscode/launch.json, README.md, RoboFile.php, lando-config/php.ini, orch/build.sh, orch/build_fe_shared.sh, orch/deploy.sh, orch/deploy_shared_install.sh, orch/deploy_shared_update.sh, orch/post_deploy.sh, orch/post_deploy_shared.sh, orch/show_file.sh
I've added a new README.md that provides guidance on how to enable xdebug on phpstorm and vscode.
Let me know if you can get the debugger fired up.
=> Closes #34: Feature/bsd 34 debug enable

robo.yml, web/modules/custom/site_wrapper/site_wrapper.module, web/themes/custom/bixal_uswds/bixal_uswds.theme, web/themes/custom/bixal_uswds/php-includes/node.inc, web/themes/custom/bixal_uswds/theme-settings.php
This MR implements validation commands which will eventually be run in a pipeline.
You can run these locally by:
`vendor/bin/robo validate:all`
I've also fixed a couple coding standards issues.
Please note that commit messages soon will be required to be in the form:
BSD [KEYWORD] #x:y
Where x is the Git Hub issue number.
And y is a space.
The keywords are: close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved
Feature branches will also be in the form:
feature/{BSD-x-y
Where x is the issue number and y is a short description lower case.
=> Closes #64 robo validate

stories/Welcome.mdx, stories/_utils/toggle.js, stories/assets/styles/global/global.scss, stories/components/button/button.scss, stories/components/button/button.stories.js, stories/components/emphasis-block/emphasis-block.scss, stories/components/header/header.js, stories/components/people-list/people-list.content.json, stories/components/people-list/people-list.html.twig, stories/components/people-list/people-list.js, stories/components/people-list/people-list.scss, stories/components/people-list/people-list.stories.js, stories/components/profile/profile.scss, stories/components/section/section.scss
Adds people list component with basic filtering. Closes #47.
> [!NOTE]  
> Filtering is basic and open to improvements. For now, this hides profiles based on matching category. The legacy version queried people data and regenerated an entirely new list.
=> BSD-47: Create people list story

config/sync/core.entity_form_display.node.bixaler.default.yml, config/sync/core.entity_view_display.node.bixaler.default.yml, config/sync/core.entity_view_display.node.bixaler.teaser.yml
=> BSD fixes #118: Removed bio field from display and form display

composer.json, composer.lock, composer.log, config/sync/core.extension.yml
Installed Email as username (email_username) and enabled it.
=> BSD closes #135: Installed Email as username (email_username).

config/sync/core.entity_form_display.media.pdf.default.yml, config/sync/core.entity_form_display.media.pdf.media_library.yml, config/sync/core.entity_view_display.media.pdf.default.yml, config/sync/core.entity_view_display.media.pdf.media_library.yml, config/sync/field.field.media.pdf.field_media_file.yml, config/sync/field.storage.media.field_media_file.yml, config/sync/language.content_settings.media.pdf.yml, config/sync/media.type.pdf.yml
=> BSD-172: Setting up PDF file type.

stories/components/people-list/people-list.content.json, stories/components/people-list/people-list.html.twig, stories/components/people-list/people-list.js, stories/components/people-list/people-list.scss
I've just added a million Buddy's to storybook!
=> Closes #173: Hide over 20 Bixalers until 'View all' is clicked

config/sync/xmlsitemap.settings.node.bixaler.yml, config/sync/xmlsitemap.settings.node.blog.yml, config/sync/xmlsitemap.settings.node.contract_vehicle.yml, config/sync/xmlsitemap.settings.node.landing_page.yml
=> BSD closes #213: Captured config for sitemap.

web/sites/default/services.yml, web/sites/updated.development.services.yml
=> BSD closes #187: Updated config for render.config.

web/modules/custom/site_wrapper/site_wrapper.module
I didn't change the x logo yet because that's not technically an issue with accessibility.
=> BSD fixes #248: Added company name to link text.

config/sync/core.entity_form_display.media.video.default.yml, config/sync/core.entity_form_display.media.video.media_library.yml, config/sync/core.entity_view_display.media.video.default.yml, config/sync/core.entity_view_display.media.video.media_library.yml, config/sync/field.field.media.video.field_media_video_file.yml, config/sync/field.storage.media.field_media_video_file.yml, config/sync/filter.format.html_text.yml, config/sync/language.content_settings.media.video.yml, config/sync/media.type.video.yml
Edit any full text field and add a media item, choose video. MP4 and WEBM supported.
=> BSD fixes #276: Add video media type. [CAPTURE CONFIG]

composer.lock, composer.log, orch/deploy_install.sh, web/sites/default/settings.lando.php
This hotfix will trigger a new build after the 1.5.0 release failed.
=> Hotfix 1.5.1

composer.lock, composer.log, config/sync/metatag.settings.yml, web/sites/default/default.settings.php
Updated composer dependencies.
=> BSD-342 : Update deps

stories/components/hero/hero.scss
Description: Request came in from Joselo via Gerardo, increased font size to meet req.
=> BSD-364: Increased font size in stories, should update in build.

stories/components/description-list/description-list.scss, web/modules/custom/bixal_default_content/content/node/ed430371-da05-4a2b-a686-80fe68d22d7c.yml
Change description list columns from 4 to 3
=> BSD fixes #369: Change columns in description list.

stories/components/contact-us/contact-us.scss, stories/components/section/section.scss
Fix a11y and display issues with CAPTCHA. Closes #376.
> [!NOTE]
> Would appreciate validating on Drupal side. In storybook, I copied over the CAPTCHA markup so I could test styles.
| ![capture-Arc-2025-03-04@2x](https://github.com/user-attachments/assets/fdb42397-b611-4f14-917c-1c413e3b3587) | ![capture-Arc-2025-03-04@2x](https://github.com/user-attachments/assets/bf88697e-03d4-409b-9fea-879ff20ddcaf) |
**Major changes**
- Actions should always be last
- The captcha spans full form width and the description is smaller
- Fixed A11Y issues with legend in primary and alt sections (dark background)
=> BSD closes #376: Fix captcha in contact form

.github/pull_request_template.md, .gitignore
Adding a pull request template for consistent formatting and faster creation.
Closes #378.
This PR follows the template format. I've create a template in the `.github` directory following their guidance[^1].
[^1]: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> BSD fixes #378: Create a pull request template

stories/Welcome.mdx, stories/assets/styles/global/global.scss, stories/assets/styles/utils/mixins/_heading-border.scss, stories/components/footer/footer.scss, stories/components/header/header.js, stories/components/header/header.scss
A11y improvements in the header and mobile navigation.
Closes #241.
1. Updated and simplified Color documentation
2. Improvements to `@mixin heading-border` on small screens
3. Mobile navigation improvements on zoom and small screens
If you visit `Welcome.mdx` in StorybookJS, you'll see the new state colors documented. The colors also now use the appropriate CSS color variable for easier reference.
| ![capture-Arc-2025-03-06@2x](https://github.com/user-attachments/assets/a9ab329c-98b2-41dd-8b53-a85ec8ac2dbc) |  ![capture-Arc-2025-03-06@2x](https://github.com/user-attachments/assets/8527c079-362a-4d9c-9645-a0618db99d56)   |
Now styles are consistent and clear across browsers.
| …
=> BSD-241: Improve header accessibility

composer.lock, composer.log
Updating composer dependencies.
=> BSD fixes #399: Updated dependencies.

stories/components/icon/icon.stories.js
Adds a storybook only decorator to see the color updates in real time.
https://github.com/user-attachments/assets/fc29c0bb-3719-4204-9eb9-f05133a595ac
Closes #410.
Adds a storybook decorator to avoid adding redundant code in the component itself.
1. Visit icon story
2. Use the color control to define a custom color
3. See the icons change color
=> BSD fixes #410: Add color decorator to see icon colors

README.md, stories/assets/styles/global/global.scss
> [!NOTE]
> This is a progressive enhancement and supported in most browsers, **except** Firefox.
> <img width="400" alt="capture-Arc-2025-04-03@2x" src="https://github.com/user-attachments/assets/6d4e3cb5-20b6-4614-87f1-c914c588a0a2"/>
> https://developer.mozilla.org/en-US/docs/Web/CSS/@view-transition
Adds simple CSS page view transitions for smoother page navigation.
**Before**
Traditional navigation where pages jump from one to another.
https://github.com/user-attachments/assets/cf07a4cd-9699-4661-925d-e3c0b42a0560
**After**
You should see a smooth transition as you navigate the lando site.
https://github.com/user-attachments/assets/88bbdac0-3384-4df2-a640-7cfeca147f15
Closes #407.
Best to test on lando site to really see the difference.
Users should be able to disable if they have …
=> BSD-407: Add page view transitions for smoother site navigation

README.md, composer.json, composer.lock, composer.log, config/sync/core.entity_form_display.node.blog.default.yml, config/sync/core.entity_form_display.node.case_study.default.yml, config/sync/core.entity_form_display.node.contract_vehicle.default.yml, config/sync/core.entity_form_display.node.landing_page.default.yml, config/sync/core.entity_view_display.node.blog.default.yml, config/sync/core.entity_view_display.node.blog.hero_section.yml, config/sync/core.entity_view_display.node.blog.teaser.yml, config/sync/core.entity_view_display.node.case_study.default.yml, config/sync/core.entity_view_display.node.case_study.teaser.yml, config/sync/core.entity_view_display.node.contract_vehicle.default.yml, config/sync/core.entity_view_display.node.contract_vehicle.hero_section.yml, config/sync/core.entity_view_display.node.contract_vehicle.teaser.yml, config/sync/core.entity_view_display.node.landing_page.default.yml, config/sync/core.entity_view_display.node.landing_page.hero_section.yml, config/sync/core.entity_view_display.node.landing_page.teaser.yml, config/sync/core.extension.yml, config/sync/field.field.node.blog.field_metatags.yml, config/sync/field.field.node.case_study.field_metatags.yml, config/sync/field.field.node.contract_vehicle.field_metatags.yml, config/sync/field.field.node.landing_page.field_metatags.yml, config/sync/field.storage.node.field_metatags.yml, config/sync/metatag.metatag_defaults.front.yml, config/sync/metatag.metatag_defaults.node__case_study.yml, config/sync/metatag.metatag_defaults.node__contract_vehicle.yml, config/sync/metatag.metatag_defaults.node__landing_page.yml, config/sync/metatag.settings.yml
This PR sets default SEO meta tags for several content types and adds a metatag field so editors can easily update or override them for each page.
Before/after using lighthouse on a Contract Vehicle page:
Closes #457.
By default, content uses `[node:summary]` for the metatag description. This is why it doesn't appear on content types, like Case Study or Landing Page.
On the `/admin/config/search/metatag` page I've added additional descriptions for:
- Front page
- Content: Case Study
- Content: Landing Page
- Content: Contract Vehicle
I've also added a new metatags field to these content types so the metatag values can be overridden.
1. Pull branch and run `lando rebuild -y`
2. Visit these types of pages and confirm a meta description in `<head>`  exists:
- …
=> BSD-457: Allow SEO meta tags to be editable
