Bixal/bixal-site-drupal

stories/assets/styles/global/global.scss
stories/components/description-list/description-list-base.html.twig
stories/components/description-list/description-list-collection-base.html.twig
stories/components/description-list/description-list-collection.html.twig
stories/components/description-list/description-list.html.twig
stories/partials/media-image.html.twig
vite.config.js
web/themes/custom/bixal_uswds/bixal_uswds.info.yml
web/themes/custom/bixal_uswds/templates/media/media--image--description-list.html.twig
web/themes/custom/bixal_uswds/templates/media/media--image.html.twig
web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--description-list-collection.html.twig
web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--description-list.html.twig

I'm kind of torn on the implementation here, because it took some extra scaffolding but I think it's pretty clean.
Instead of adding an extra wrapper around the description list image, I merged the 2 elements. This was required because the outer one added a position relative (for the vertical line) and the inner one (in Drupal) added contextual region class (for Drupal contextual edit links) which also added a position relative. Since they were nested position relatives, the outer one did not work (the vertical line). Now the vertical line class and contextual region class are in the same wrapper (a <figure> in this case).
Also, I've re-implemented description list collection so it can easily be used in Drupal. Basic gist is that:
* SB components should extend a 'base' template.
* The …

Fixes #77: Description list missing vertical line when logged in

---

config/sync/core.entity_view_display.node.blog.teaser.yml
stories/components/blurb/blurb-base.html.twig
stories/components/blurb/blurb-collection-base.html.twig
stories/components/blurb/blurb-collection-featured.content.json
stories/components/blurb/blurb-collection.content.json
stories/components/blurb/blurb-collection.html.twig
stories/components/blurb/blurb.html.twig
stories/components/blurb/blurb.scss
stories/components/blurb/blurb.stories.js
stories/components/button/button.html.twig
stories/components/description-list/description-list.html.twig
stories/components/section/section.html.twig
stories/pages/careers/careers.stories.js
stories/pages/case-studies-landing/case-studies-landing.html.twig
stories/pages/case-studies-landing/case-studies-landing.stories.js
stories/pages/case-study/case-study.html.twig
stories/pages/case-study/case-study.stories.js
web/themes/custom/bixal_uswds/templates/node/node--blog--teaser.html.twig
web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--blurb-collection.html.twig
web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--blurb.html.twig
web/themes/custom/bixal_uswds/templates/views/views-view--blog.html.twig

Created Case Study landing page and placeholder case study. Closes #53.
1. New variant called `Blurb Collection Featured`.
2. Blurbs are now in an unordered list, instead of a `div`.
**Blurb featured**
Some of the images are slightly larger — _ex: Educating the public vs  Delivering Digital Communications for Food Security._ On live there's a fixed height and styles to make them all the same. We should **avoid** this pattern and set consistent images by default to avoid warping and/or blurriness on small screens.
The first item will always be full width.
Image sizes below are suggested for this component.
**Featured**
Large: 1350px
Small: 516px
**Regular** 
670px

BSD-53: Case studies

---

config/sync/system.action.user_add_role_action.site_admin.yml
config/sync/system.action.user_remove_role_action.site_admin.yml
config/sync/system.site.yml
config/sync/user.mail.yml
config/sync/user.role.site_admin.yml
config/sync/user.settings.yml
web/modules/custom/bixal_default_content/content/user/abd579e2-1336-437d-9c29-d7cee2076b71.yml

_Notes_
- un: site-admin pw: site-admin
- had to grant access to admin theme and menus but the only thing available is adding editors
- Changed some site settings for registration and removal of user shifts content to user 1

BSD closes #102: Created site-admin role, created site-admin test user

---

composer.json
composer.lock
composer.log
config/sync/chosen.settings.yml
config/sync/core.entity_form_display.node.bixaler.default.yml
config/sync/core.extension.yml

*Notes for testing*
- lando start && lando si
- Go to this page -> http://bixalcom.lndo.site/admin/config/user-interface/chosen
- If you see an error message regarding the library, run 'drush chosenplugin', this is what I had to run to get it to work, however I couldn't replicate the error message by deleting vendor so I assume it is added somewhere. If that is the case, maybe we have to add that command after set-hp.
- Add a bixaler to see the module in action

BSD closes #103: Install and configure chosen for taxonomy ref fields

---

web/themes/custom/bixal_uswds/php-includes/page.inc

Rearranged social icons to move LinkedIn to far left, and removed medium

BSD fixes #146: Rearranging social icons

---

config/sync/core.entity_view_display.paragraph.blurb_collection.default.yml
config/sync/field.field.paragraph.blurb_collection.field_featured.yml
web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--blurb-collection.html.twig

Real interesting problem here! So the way it was checking for featured was if the field existed. This works for some things, however if 'featured' was ever checked regardless of switching back, the field would have some value in it. You can switch to featured in a dev environment, then switch it back and it'll stay as featured. This PR should fix that issue!

BSD closes #174: Changed field to true/false, fixed var in template, set a default.

---

web/themes/custom/bixal_uswds/src/js/bx-global.js

I tested this by copying and pasting my diff in the console on prod. Hopefully this works after merging into prod. Since it was such a specific piece of code, I just put it in our general library. Since we have other sites on Platform though, I might abstract this chunk so we can reuse later.

BSD fixes #179: Added function to decode CF email protection.

---

.platform.app.yaml

See https://feature-bsd-202-webp-f5a6foa-tsvj5tw7p3f66.us.platformsh.site/our-work/sba for working images now in the contract vehicles.

BSD fixes #202: Allow access to webp files in the default route on platform

---

web/themes/custom/bixal_uswds/src/sass/styles.scss
web/themes/custom/bixal_uswds/templates/layout/html.html.twig

Super tiny now
https://pr-233-imhdbhq-tsvj5tw7p3f66.us.platformsh.site/

BSD fixes #232: Use only uswds core and usa skipnav instead of ALL of all uswds components.

---

web/modules/custom/bixal_captcha/bixal_captcha.module

Send a sitewide contact form with a company that does not have 'google' in it, a mail should be sent.
Send a sitewide contact form with a company that does have 'google' in it, a mail should be sent.

BSD fixes #274: Dont allow contact submissions with a company of google to be submitted.

---

README.md

This PR updates the README.md with guidance on branch and commit conventions. As well as a preview link to the storybook preview.
Helpful to those wanting to contribute to the codebase. Based on guidance in `robo.yml`.
Closes #295.

BSD fixes #295: Add branch and commit guidance to README.

---

.platform/applications.yaml
config/sync/field.field.media.image.field_media_image.yml
config/sync/field.field.media.pdf.field_media_file.yml
config/sync/field.field.media.video.field_media_video_file.yml
lando-config/php.ini
orch/deploy_install.sh
web/sites/default/settings.memcache.php
web/sites/default/settings.redis.php

Image & PDF 100 MB: /admin/structure/media/manage/image/fields/media.image.field_media_image, /admin/structure/media/manage/pdf/fields/media.pdf.field_media_file
Video 300 MB: /admin/structure/media/manage/video/fields/media.video.field_media_video_file
/admin/reports/status/php post_max_size & upload_max_filesize 300M
Lando & https://feature-bsd-318-file-236uqiq-tsvj5tw7p3f66.us.platformsh.site/ should be identical.

BSD fixes #318: Upload file size limit

---

.lando.dist.yml
config/sync/core.entity_form_display.sitewide_alert.sitewide_alert.default.yml
config/sync/sitewide_alert.settings.yml
config/sync/user.role.site_admin.yml
package.json
stories/_index.scss
stories/assets/styles/global/global.scss
stories/assets/styles/utils/mixins/_alert-base-styles.scss
stories/components/alert/alert.html.twig
stories/components/alert/alert.scss
stories/components/alert/alert.stories.js
stories/components/site-alert/site-alert.html.twig
stories/components/site-alert/site-alert.scss
stories/components/site-alert/site-alert.stories.js
web/modules/custom/bixal_default_content/content/sitewide_alert/d5ff2381-ddfc-44b1-93cd-627d79bd662f.yml
web/themes/custom/bixal_uswds/templates/content/sitewide-alert.html.twig

Two new alert components with variants. Based on USWDS guidance. Closes #329.
1. **Alert**. An inline alert that can be used for form messages. Includes variants for: info, warning, and error.
2. **Site alert**. Full width alerts that go at the top of the page and span the entire width. Use these for alerts that are important for users to see first. Do **not** use this for form error handling (use alert instead).
**Base**
**Info**
**Warning**
**Error**
**Base**
**Info**
**Warning**
**Urgent** for urgent, time sensitive notifications.

BSD fixes #329: Create initial alert component

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/field.field.media.video.field_media_video_file.yml
config/sync/user.role.site_admin.yml

* Add the [file_resup](https://drupal.org/project/file_resup) module to enable uploads larger than supported by the webserver or PHP
* Enable on the Video media type.
With this, a video file can be added to a node via CKEditor's Add Media button.

BSD-340: Add the file_resup module to allow large uploads to file fields, enable for the Video file field.

---

stories/components/section/section.html.twig
stories/partials/section-title.html.twig
web/modules/custom/bixal_default_content/content/node/49da5723-5914-4252-a7aa-c27d3efd8fb3.yml
web/themes/custom/bixal_uswds/templates/node/node--case-study--full.html.twig

Creates a node template for the case study content type and exports a single case study so it can be easily reviewed at /our-work/digital-apex.
Testing:
`lando si` then visit the above link.

BSD-336: Add case study node template

---

web/sites/default/settings.lando.php
web/sites/default/settings.memcache.php
web/sites/default/settings.platformsh.php
web/sites/default/settings.redis.php

To Reproduce (Must be done on a different branch)
1.     Load the site
2.     `lando drush cg entity_field_map discovery`
3.     Note the cache value.
4.     `lando drush cr`
5.     `lando drush cg entity_field_map discovery`
6.     Note the cache value is still there.
After switching to the above, the cache value should be gone after `lando drush cr`.
The problem was that the settings changes needed to be INSIDE the function, otherwise they won't be applied again. Drush initializes the site multiple times and wipes it out, making you use the default cache bin 'memory'.

BSD fixes #338: Allow cache to be cleared with Drush again.

---

stories/assets/styles/global/global.scss
stories/components/button/button.scss

Adds an underline to links that look like buttons to make it clear that it is a link. 
Closes #247.
Adjusted default link styles and reverted the text decoration property on links that have the button class.
Links that look like buttons should have an underline.
**Example**
The "Work with us" in the footer:

BSD-247: For a11y, add underline to links that look like buttons.

---

stories/components/footer/footer.stories.js
web/modules/custom/site_wrapper/site_wrapper.module

Gives the footer social nav a unique aria label to address a11y issue of duplicate labels.
Closes #98.
Gave a unique label to the Footer social nav.
Should read:
```
Bixal social links
```
1. Visit the profile story
2. Confirm that the aria-label on social navs are different

BSD-98: Add a unique aria label to footer social links

---

stories/_utils/toggle.js
stories/assets/styles/global/global.scss
stories/components/people-list/people-list.html.twig
stories/components/people-list/people-list.js
stories/components/people-list/people-list.scss

This work adds some accessibility improvements to the current People filter component.
Closes #242.
The original accessibility recommendation was to completely remove it, which seems like a harsh and time intensive route. These changes require some markup changes:
1. A screen reader only counter for total number of visible elements.
2. A fieldset for wrapping the dropdown items
3. Aria attributes to improve context in screen readers
4. Dropdown now closes via <kbd>ESC</kbd> and when out of focus.
You'll need a screen reader to test the full changes, but there are some things you can test without:
1. On opening the dropdown, you should be able to use the arrow keys to navigate.
2. You can close the dropdown with <kbd>Esc</kbd> or by switching focus.
3. Inspect and see the `sr-only` …

BSD-242: Improve about filter accessibility

---

.gitignore
.storybook/main.js
README.md
stories/components/icon/icon-demo.html.twig
stories/components/icon/icon.html.twig
stories/components/icon/icon.scss
stories/components/icon/icon.stories.js

Adds support for using USA Icon inline.
**How to use**
```twig
{% include "@components/icon/icon.html.twig" with {
icon_name: "alternate_email",
icon_size: 9
} %}
```
Supports all icons listed in https://designsystem.digital.gov/components/icon/.
Closes #398.
I've added the USWDS directory to storybook so we can resolve the icons. In the Drupal theme the path looks like this:
```diff
- {{ directory }}/dist/assets/img/sprite.svg#rss_feed"
+ {% include "@components/icon/icon.html.twig" with {
+  icon_path: directory ~ "/dist/assets/img/sprite.svg"
+  icon_name: "alternate_email",
+  icon_size: 9
+ } %}
```
1. Run storybook locally via `npm run storybook:local`
2. Search for icons in nav, you should see three variants
3. Icons should render correctly

BSD-398: icon component

---

web/themes/custom/bixal_uswds/templates/views/views-view-unformatted.html.twig

Prevents an issue with malformed HTML where divs are direct children of an unordered list
Fixes malformed HTML that's causing an a11y issue. Divs should **not** be direct children of lists.
Closes #415.
Directly rendering content if `row_classes[0]` is an empty string.
1. Locally, visit https://bixalcom.lndo.site/blog
2. Inspect the blog teasers
3. The markup should be `ul > li`

BSD-415: Avoid wrapping unformatted rows if classes are empty

---

composer.patches.json

Applies a core patch to put the class back that makes the modal 75% of the width of one's screen.
Closes #430
Edit any piece of content with a WYSIWYG, when adding a media item the modal should be 75% width.

BSD-430: Apply patch to put back the modal class.

---

web/themes/custom/bixal_uswds/templates/form/input.html.twig

Adds Bixal theme button classes to submit and reset buttons.
| ![Image](https://github.com/user-attachments/assets/5fb7802a-84a8-4c1d-8aa9-6aa22151c4ec) |  ![capture-Arc-2025-04-14@2x](https://github.com/user-attachments/assets/e1a6bae6-78c8-4928-a718-eec5d5f1cb11)       |
Closes #427
I've added the `bix-button` and `bix-button--unstyled` to `bixal_uswds/templates/form/input.html.twig`.
1. Visit the login page locally `https://bixalcom.lndo.site/user/login`
2. Verify that the submit button is now styled

BSD-427: Add Bixal button classes to form buttons

---

web/themes/custom/bixal_uswds/gulpfile.js

Updated the order of gulp tasks to fix missing directory error.
Closes #435.
Matches the init pattern in USWDS compile, where the assets are copied before compiling.
https://github.com/uswds/uswds-compile/blob/cc5f8c7298a1716b67a590f6bcebebdb7a4beaaf/gulpfile.js#L303
1. Checkout this branch
2. Delete the `bixal_uswds/dist` directory
```bash
rm -rf web/themes/custom/bixal_uswds/dist/
```
3. Run lando build node task
```bash
lando build_node
```

BSD fixes #435: Update order of compile scripts.

---

.platform/applications.yaml
README.md

Removes storybook from being build on production.
Stop the build process if PLATFORM_ENVIRONMENT_TYPE is production. The /sb/ route is still in place and shows a platform 404 instead of a Drupal one, but I think that's OK. 
I built this branch here https://feature-bsd-439-remove-pprxtii-tsvj5tw7p3f66.us.platformsh.site/sb/ but we won't be able to test the removal on prod until it's pushed. Unfortunately you can only set one prod type env. You can see that sb is still being built.

BSD fixes #439: Remove storybook from prod

---

stories/components/hero/hero.scss

A quick change to hero background images, from position `top` to `center`.
Closes #460.
| ![capture-Arc-2025-06-04@2x](https://github.com/user-attachments/assets/26f8f4ca-8ce2-4ae4-927b-9da8a18f97e9) |       ![capture-Arc-2025-06-04@2x](https://github.com/user-attachments/assets/e1274dfe-0184-425e-a58a-13e5b5fb8854)  |

BSD fixes #460: Center hero images

---

README.md
stories/assets/styles/global/global.scss
stories/components/alert/alert.html.twig
stories/components/alert/alert.scss
stories/components/alert/alert.stories.js
web/themes/custom/bixal_uswds/src/sass/drupal-system/system.scss
web/themes/custom/bixal_uswds/templates/misc/status-messages.html.twig

Adds a success alert variant and Drupal status messages now use Bixal Alert component.
| ![capture-KEu9OrXe-2025-09-03](https://github.com/user-attachments/assets/681fe62f-dadd-4732-a926-9ec9864961f8) |   ![capture-8ZwiYISb-2025-09-03](https://github.com/user-attachments/assets/f308c26d-bf37-47d4-a6a4-41c0908ae6a2)     |
Closes #402
- Replaces USA Alert with Bixal Alert
- Adds a wrapper class to contain alerts
- Improved a11y by setting `role="alert"` to urgent, warning, and error variants
- Allows custom body block markup instead of plain text only
- Adds success variant
- Adjustments to icon positioning and spacing
- Added a new success variant in Storybook
- Updated README
- Used logical properties to replace `margin-left/right/etc.` to better …

BSD-402: Use alerts for Drupal status messages
